[package]
name = "asteroid"
version = "0.1.0"
authors = ["Oragon Efreet <kevin.dorange@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#bevy = "0.4"
bevy = { git = "https://github.com/bevyengine/bevy" }


